//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raspisanie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lession_Employee
    {
        public int id_lession_employee { get; set; }
        public int FK_id_lession { get; set; }
        public int FK_id_employee { get; set; }
    
        public virtual Lessions Lessions { get; set; }
        public virtual Users Users { get; set; }
    }
}
