//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raspisanie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lession_Child
    {
        public int id_lession_child { get; set; }
        public int FK_id_Lession { get; set; }
        public int id_group_child { get; set; }
        public int numder_classroom { get; set; }
        public System.DateTime date_time_child { get; set; }
    
        public virtual Group_Child Group_Child { get; set; }
        public virtual Lessions Lessions { get; set; }
    }
}
