//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raspisanie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaspisanieEntities : DbContext
    {
        public RaspisanieEntities()
            : base("name=RaspisanieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Child> Child { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Group_Child> Group_Child { get; set; }
        public virtual DbSet<Lession_Child> Lession_Child { get; set; }
        public virtual DbSet<Lession_Employee> Lession_Employee { get; set; }
        public virtual DbSet<Lessions> Lessions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
